// 各设置分区的初始数据：按「每分区一张类型化表」建模，
// 键即对应 Prisma 模型的列名；无法落到专列的参数值放入 fields JSON。
export const SEED_SETTINGS: Record<string, Record<string, unknown>[]> = {
  connectors: [
    {
      name: 'X榜单API',
      description: '采集五个地区Top30',
      enabled: true,
      baseUrl: 'https://api.provider.example/v1',
      authMethod: 'API Key（加密保存）',
      syncFrequency: '每1小时',
      timeoutRetry: '30秒 · 最多3次',
      fallback: '保留上次成功快照并告警',
    },
    {
      name: 'X热门帖子API',
      description: '每地区获取最多3条默认热门帖子',
      enabled: true,
      baseUrl: 'https://api.provider.example/v1',
      syncFrequency: '每1小时',
      fallback: '保留上次成功快照并告警',
    },
    {
      name: 'X帖子指标API',
      description: '浏览、点赞、回复、转发追踪',
      enabled: false,
      baseUrl: 'https://api.provider.example/v1',
      fields: { metrics: '浏览、点赞、回复、转发' },
    },
    {
      name: '内容生成模型',
      description: '执行基础账号与人设Skills',
      enabled: true,
      baseUrl: '模型接口',
      authMethod: 'API Key（加密保存）',
      syncFrequency: '按需',
    },
  ],

  monitoring: [
    {
      name: '榜单采集频率',
      description: '相邻成功快照比较',
      enabled: true,
      compareWindow: '相邻成功快照比较',
      fields: { frequency: '每1小时' },
    },
    {
      name: '前5触发',
      description: '任一目标榜单',
      enabled: true,
      regions: 'Worldwide / US / UK / Japan / Korea',
      threshold: '进入前5',
    },
    {
      name: '急剧上升',
      description: '相邻成功快照',
      enabled: true,
      compareWindow: '相邻成功快照',
      threshold: '上升≥10位',
    },
    {
      name: '跨区异动',
      description: '同一Event',
      enabled: true,
      regions: '≥2地区',
      action: '形成/归并Event并自动响应',
    },
  ],

  topics: [
    {
      name: 'AI',
      description: '语义词与示例Event',
      enabled: true,
      keywords: 'GPT, OpenAI, Claude, Kimi, AI model',
      positiveExamples: 'GPT-6发布；Kimi开源新模型',
      negativeExamples: '仅出现字母AI但无行业含义',
      action: '立即自动响应',
    },
    {
      name: '预测市场',
      description: '语义词与示例Event',
      enabled: true,
      keywords: 'prediction market, 预测市场, Polymarket',
      positiveExamples: 'Polymarket上线新市场',
      negativeExamples: '与预测市场无关的普通讨论',
      action: '立即自动响应',
    },
    {
      name: '加密监管',
      description: '语义词与示例Event',
      enabled: true,
      keywords: 'crypto regulation, 加密监管, SEC, 监管政策',
      positiveExamples: 'SEC新规发布',
      negativeExamples: '仅讨论币价波动',
      action: '立即自动响应',
    },
    {
      name: '体育大赛',
      description: '语义词与示例Event',
      enabled: true,
      keywords: '世界杯, NBA, 欧冠, 体育赛事',
      positiveExamples: '世界杯赛程公布',
      negativeExamples: '普通比赛结果闲聊',
      action: '立即自动响应',
    },
  ],

  accounts: [
    {
      name: 'WatcherGuru快讯号',
      description: '快讯型 · 全量覆盖',
      enabled: true,
      xAccountId: '@WatcherGuru',
      type: '快讯型 · 全量覆盖',
      skill: 'content-operator/SKILL.md',
      frequency: '10–15条/日或按Skill',
      onFailure: '保留任务并上报异常',
    },
    {
      name: 'PredX Explain',
      description: '解释翻译型 · 全量覆盖',
      enabled: true,
      xAccountId: '@PredX_Explain',
      type: '解释翻译型 · 全量覆盖',
      skill: 'content-operator/SKILL.md',
      onFailure: '保留任务并上报异常',
    },
    {
      name: 'PredX Markets',
      description: '产品承接型 · 相关性门槛',
      enabled: true,
      xAccountId: '@PredX_Markets',
      type: '产品承接型 · 相关性门槛',
      skill: 'content-operator/SKILL.md',
      onFailure: '保留任务并上报异常',
    },
    {
      name: 'Domer',
      description: '人设Skill自主判断',
      enabled: false,
      xAccountId: '@Domer',
      type: '人设Skill自主判断',
      skill: 'content-operator/SKILL.md',
      onFailure: '保留任务并上报异常',
    },
  ],

  product: [
    {
      name: '产品基础信息',
      description: '名称、行业、用户和能力',
      enabled: true,
      url: 'https://predx.example.com/markets/...',
      targetUsers: '关注时事、体育、加密与宏观的用户',
      capability: '真实存在的预测市场与概率信息',
      lastSync: '2026-08-13 10:00',
    },
    {
      name: '禁止承诺',
      description: '收益、概率和未上线能力',
      enabled: true,
      forbidden: '收益承诺、虚构市场、确定性结果',
    },
    {
      name: '市场页面目录',
      description: '可承接Event的真实页面',
      enabled: true,
      url: 'https://predx.example.com/markets',
      lastSync: '2026-08-13 10:00',
      fields: { pages: '3个页面' },
    },
  ],

  risk: [
    {
      name: '平台规则风险',
      description: '重复、垃圾信息、受限表达',
      enabled: true,
      rule: '重复、垃圾信息、受限表达',
      lowAction: '正常交付',
      midAction: '自动改写并重检，最多3次',
      highAction: '禁止复制，人工处理',
      afterRelease: '必须重新预检',
    },
    {
      name: '事实风险',
      description: '无依据确定化、冲突、过时',
      enabled: true,
      rule: '无依据确定化、冲突、过时',
      lowAction: '正常交付',
      midAction: '自动改写并重检，最多3次',
      highAction: '禁止复制，人工处理',
      afterRelease: '必须重新预检',
    },
    {
      name: '法律/品牌风险',
      description: '隐私、版权、冒犯',
      enabled: true,
      rule: '隐私、版权、冒犯',
      lowAction: '正常交付',
      midAction: '自动改写并重检，最多3次',
      highAction: '禁止复制，人工处理',
      afterRelease: '必须重新预检',
    },
    {
      name: '产品与金融风险',
      description: '虚构功能、收益承诺',
      enabled: true,
      rule: '虚构功能、收益承诺',
      lowAction: '正常交付',
      midAction: '自动改写并重检，最多3次',
      highAction: '禁止复制，人工处理',
      afterRelease: '必须重新预检',
    },
  ],

  tracking: [
    {
      name: '发布后0–24小时',
      description: '数据抓取频率',
      enabled: true,
      timeRange: '0–24小时',
      value: '每2小时',
      metrics: '浏览、点赞、回复、转发',
      onFailure: '发布完成 + 追踪异常',
      goodExtend: '延长至14天',
    },
    {
      name: '24小时以后',
      description: '数据抓取频率',
      enabled: true,
      timeRange: '24小时以后',
      value: '每5小时',
      metrics: '浏览、点赞、回复、转发',
      goodExtend: '延长至14天',
    },
    {
      name: '最低追踪期',
      description: '所有已发布帖子',
      enabled: true,
      value: '7天',
      metrics: '浏览、点赞、回复、转发',
    },
    {
      name: '表现良好',
      description: '48小时浏览量',
      enabled: true,
      value: '≥1,000',
      fields: { window: '48小时浏览量' },
    },
  ],

  futureSources: [
    {
      name: 'BLS官方日历',
      description: '官方网页 · 证据A',
      enabled: true,
      url: 'https://official-source.example/calendar',
      method: '官方网页',
      evidenceLevel: 'A',
      syncFrequency: '正常',
      maxStale: '按距离事件自动调整',
    },
    {
      name: '重点体育赛程',
      description: 'API/iCal · 证据A/B',
      enabled: true,
      url: 'https://official-source.example/sports',
      method: 'API / iCal',
      evidenceLevel: 'A/B',
      syncFrequency: '正常',
      maxStale: '按距离事件自动调整',
    },
    {
      name: '全球节日日历',
      description: '系统内置 · 证据B',
      enabled: true,
      method: '系统内置',
      evidenceLevel: 'B',
      syncFrequency: '正常',
    },
    {
      name: '人工批量导入',
      description: 'CSV/Excel · 重新评估',
      enabled: true,
      method: 'CSV/Excel',
      evidenceLevel: '重新评估',
      syncFrequency: '正常',
    },
  ],

  permissions: [
    {
      name: '普通运营',
      description: '选择、复制、回填、一般异常',
      enabled: true,
      scope: '选择、复制、回填、一般异常',
      overridable: '按角色限制',
      effectiveOn: '新Event/新帖子',
      auditRequirement: '记录操作者、原因与版本',
    },
    {
      name: '运营负责人',
      description: '风险解除、主题和监控配置',
      enabled: true,
      scope: '风险解除、主题和监控配置',
      overridable: '按角色限制',
      effectiveOn: '新Event/新帖子',
      auditRequirement: '记录操作者、原因与版本',
    },
    {
      name: '系统维护人员',
      description: '接口、Skills和系统规则',
      enabled: true,
      scope: '接口、Skills和系统规则',
      overridable: '按角色限制',
      effectiveOn: '新Event/新帖子',
      auditRequirement: '记录操作者、原因与版本',
    },
    {
      name: '版本策略',
      description: '新对象用新版本，在途锁旧版本',
      enabled: true,
      fields: { version: 'v2.4' },
    },
  ],
}

// 审计记录：[object, action, operator, version]
export const SEED_SETTING_AUDIT: [string, string, string, string][] = [
  ['AI主题语义词', '修改', 'Rachelyuan', 'v2.5草稿'],
  ['高风险', '解除并重检', '系统维护员', 'T-1068'],
  ['两个Signal', '合并', '运营负责人', 'EV-1841'],
  ['追踪规则', '生效', '系统', 'v2.4'],
]
